services:
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    container_name: server
    ports: 
      - "5678:5678"
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_HOST=server
      - SERVER_PORT=5678

  client_0:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_0
    depends_on:
      - server
    environment:
      - AGENCY_ID=0
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-0.csv
      - OUTPUT_FILE=/output/output-0.csv
    volumes:
      - ./input:/input
      - ./output:/output

  client_1:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_1
    depends_on:
      - server
    environment:
      - AGENCY_ID=1
      - SERVER_HOST=server
      - SERVER_PORT=5678 
      - INPUT_FILE=/input/input-1.csv
      - OUTPUT_FILE=/output/output-1.csv
    volumes:
    - ./input:/input
    - ./output:/output
  
  client_2:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_2
    depends_on:
      - server
    environment:
      - AGENCY_ID=2
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-2.csv
      - OUTPUT_FILE=/output/output-2.csv
    volumes:
      - ./input:/input
      - ./output:/output

  client_3:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_3
    depends_on:
      - server
    environment:
      - AGENCY_ID=3
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-3.csv
      - OUTPUT_FILE=/output/output-3.csv
    volumes:
      - ./input:/input
      - ./output:/output
  
  client_4:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_4
    depends_on:
      - server
    environment:
      - AGENCY_ID=4
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-4.csv
      - OUTPUT_FILE=/output/output-4.csv
    volumes:
      - ./input:/input
      - ./output:/output
  
  client_5:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_5
    depends_on:
      - server
    environment:
      - AGENCY_ID=5
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-5.csv
      - OUTPUT_FILE=/output/output-5.csv
    volumes:
      - ./input:/input
      - ./output:/output
